name: platform

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Shanghai
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    environment:
      BACKEND_UPSTREAM: host.docker.internal:8000
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    environment:
      BACKEND_UPSTREAM: host.docker.internal:8000
      FRONTEND_UPSTREAM: host.docker.internal:3000
      MQ_ADMIN_UPSTREAM: rabbitmq:15672
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
  mediamtx:
    image: bluenviron/mediamtx:1
    environment:
      MTX_RTSPTRANSPORTS: tcp,udp

volumes: # 持久化数据卷
  timescaledb-data:
    driver: local
  rabbitmq-data:
    driver: local
