name: platform

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Shanghai
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP 端口
      - "15672:15672"  # Web管理界面端口
      - "1883:1883"    # MQTT 端口
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    #      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
    command:
      - /bin/bash
      - -c
      - |
        rabbitmq-plugins enable rabbitmq_event_exchange
        rabbitmq-plugins enable rabbitmq_mqtt --offline
        docker-entrypoint.sh rabbitmq-server
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes: # 持久化数据卷
  timescaledb-data:
    driver: local
  rabbitmq-data:
    driver: local