## RabbitMQ core listeners
listeners.tcp.default = 5672
management.tcp.port = 15672

## MQTT plugin listener
mqtt.listeners.tcp.default = 1883

## Authentication and authorisation backends
auth_backends.1 = internal
auth_backends.2 = cache
auth_cache.cached_backend = http
auth_cache.cache_ttl = 60000
auth_cache.cache_refusals = false
auth_http.http_method = post
auth_http.user_path = http://host.docker.internal:8000/mq/auth/user
auth_http.vhost_path = http://host.docker.internal:8000/mq/auth/vhost
auth_http.resource_path = http://host.docker.internal:8000/mq/auth/resource
auth_http.topic_path = http://host.docker.internal:8000/mq/auth/topic

## Development-friendly defaults
loopback_users.guest = false
