"""add rabbitmq permission bindings

Revision ID: 4afb50eb0a2d
Revises: 2abf087db856
Create Date: 2026-03-12 16:30:18.072509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.common.permissions import MESSAGING_BROKER_MANAGE

# revision identifiers, used by Alembic.
revision: str = '4afb50eb0a2d'
down_revision: Union[str, Sequence[str], None] = '2abf087db856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rabbitmq_permission_binding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='业务权限ID'),
    sa.Column('check_type', sa.Enum('user', 'vhost', 'resource', 'topic', name='rabbitmqauthcheckenum'), nullable=False, comment='对应 RabbitMQ HTTP 认证后端的检查类型'),
    sa.Column('vhost_pattern', sa.String(length=255), nullable=False, comment='vhost 匹配模式, 使用 shell-style wildcard'),
    sa.Column('resource_type', sa.Enum('exchange', 'queue', 'topic', name='rabbitmqresourcetypeenum'), nullable=True, comment='资源类型, resource/topic 检查时可用'),
    sa.Column('resource_name_pattern', sa.String(length=255), nullable=True, comment='exchange/queue 名称匹配模式, 使用 shell-style wildcard'),
    sa.Column('permission_level', sa.Enum('configure', 'write', 'read', name='rabbitmqpermissionlevelenum'), nullable=True, comment='RabbitMQ configure/write/read 权限级别'),
    sa.Column('routing_key_pattern', sa.String(length=255), nullable=True, comment='topic 路由键匹配模式, 使用 AMQP topic wildcard'),
    sa.Column('rabbitmq_tag', sa.Enum('management', 'policymaker', 'monitoring', 'administrator', name='rabbitmqtagenum'), nullable=True, comment='RabbitMQ 管理标签, 仅 /auth/user 返回使用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rabbitmq_permission_binding_permission_id'), 'rabbitmq_permission_binding', ['permission_id'], unique=False)
    # ### end Alembic commands ### 

    conn = op.get_bind()
    permission_table = sa.Table('permission', sa.MetaData(), autoload_with=conn)
    role_table = sa.Table('role', sa.MetaData(), autoload_with=conn)
    role_permission_table = sa.Table('role_permission', sa.MetaData(), autoload_with=conn)
    rabbitmq_binding_table = sa.Table('rabbitmq_permission_binding', sa.MetaData(), autoload_with=conn)

    op.bulk_insert(
        permission_table,
        [
            {
                'code': MESSAGING_BROKER_MANAGE.code,
                'name': MESSAGING_BROKER_MANAGE.name,
            }
        ],
    )

    admin_role_id = conn.execute(
        sa.select(role_table.c.id).where(role_table.c.code == 'admin')
    ).scalar_one()
    permission_id = conn.execute(
        sa.select(permission_table.c.id).where(permission_table.c.code == MESSAGING_BROKER_MANAGE.code)
    ).scalar_one()

    op.bulk_insert(
        role_permission_table,
        [
            {
                'role_id': admin_role_id,
                'permission_id': permission_id,
            }
        ],
    )

    op.bulk_insert(
        rabbitmq_binding_table,
        [
            {
                'permission_id': permission_id,
                'check_type': 'user',
                'vhost_pattern': '*',
                'resource_type': None,
                'resource_name_pattern': None,
                'permission_level': None,
                'routing_key_pattern': None,
                'rabbitmq_tag': 'administrator',
            },
            {
                'permission_id': permission_id,
                'check_type': 'vhost',
                'vhost_pattern': '*',
                'resource_type': None,
                'resource_name_pattern': None,
                'permission_level': None,
                'routing_key_pattern': None,
                'rabbitmq_tag': None,
            },
            {
                'permission_id': permission_id,
                'check_type': 'resource',
                'vhost_pattern': '*',
                'resource_type': None,
                'permission_level': 'configure',
                'resource_name_pattern': '*',
                'routing_key_pattern': None,
                'rabbitmq_tag': None,
            },
            {
                'permission_id': permission_id,
                'check_type': 'resource',
                'vhost_pattern': '*',
                'resource_type': None,
                'permission_level': 'write',
                'resource_name_pattern': '*',
                'routing_key_pattern': None,
                'rabbitmq_tag': None,
            },
            {
                'permission_id': permission_id,
                'check_type': 'resource',
                'vhost_pattern': '*',
                'resource_type': None,
                'permission_level': 'read',
                'resource_name_pattern': '*',
                'routing_key_pattern': None,
                'rabbitmq_tag': None,
            },
            {
                'permission_id': permission_id,
                'check_type': 'topic',
                'vhost_pattern': '*',
                'resource_type': None,
                'permission_level': 'write',
                'resource_name_pattern': '*',
                'routing_key_pattern': '#',
                'rabbitmq_tag': None,
            },
            {
                'permission_id': permission_id,
                'check_type': 'topic',
                'vhost_pattern': '*',
                'resource_type': None,
                'permission_level': 'read',
                'resource_name_pattern': '*',
                'routing_key_pattern': '#',
                'rabbitmq_tag': None,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    permission_table = sa.Table('permission', sa.MetaData(), autoload_with=conn)
    role_permission_table = sa.Table('role_permission', sa.MetaData(), autoload_with=conn)
    rabbitmq_binding_table = sa.Table('rabbitmq_permission_binding', sa.MetaData(), autoload_with=conn)

    permission_id = conn.execute(
        sa.select(permission_table.c.id).where(permission_table.c.code == MESSAGING_BROKER_MANAGE.code)
    ).scalar()

    if permission_id:
        conn.execute(
            rabbitmq_binding_table.delete().where(rabbitmq_binding_table.c.permission_id == permission_id)
        )
        conn.execute(
            role_permission_table.delete().where(role_permission_table.c.permission_id == permission_id)
        )
        conn.execute(
            permission_table.delete().where(permission_table.c.id == permission_id)
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rabbitmq_permission_binding_permission_id'), table_name='rabbitmq_permission_binding')
    op.drop_table('rabbitmq_permission_binding')
    # ### end Alembic commands ###
