"""init schema

Revision ID: df8ee19aa3da
Revises: 
Create Date: 2026-01-09 01:21:03.233697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8ee19aa3da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False, comment='权限唯一标识代码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='权限名称'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='updated time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False, comment='角色唯一标识代码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='角色名称'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='updated time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_code'), 'role', ['code'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unified_id', sa.String(length=32), nullable=False, comment='统一身份ID, 学号/教工号'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='密码哈希'),
    sa.Column('user_type', sa.Enum('student', 'teacher', 'admin', name='usertypeenum'), nullable=False, comment='用户类型'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效账号'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='genderenum'), nullable=True, comment='性别'),
    sa.Column('birthdate', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='updated time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_unified_id'), 'user', ['unified_id'], unique=True)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('student_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_type', sa.Enum('undergraduate', 'master', 'phd', name='studenttypeenum'), nullable=False, comment='学生类型'),
    sa.Column('college', sa.String(length=128), nullable=True, comment='学院'),
    sa.Column('major', sa.String(length=128), nullable=True, comment='专业'),
    sa.Column('enrollment_year', sa.Integer(), nullable=True, comment='入学年份'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('teacher_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True, comment='系别'),
    sa.Column('title', sa.String(length=128), nullable=True, comment='职称'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='updated time'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 删除表和索引
    op.drop_table('user_role')
    op.drop_table('teacher_profile')
    op.drop_table('student_profile')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_user_unified_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_code'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_table('permission')
    # 删除自定义枚举类型
    op.execute('DROP TYPE IF EXISTS usertypeenum')
    op.execute('DROP TYPE IF EXISTS genderenum')
    op.execute('DROP TYPE IF EXISTS studenttypeenum')